destination: ./_site
lsi:         false
port:        4000
highligher:  true
markdown:    kramdown
permalink:   date
rdiscount:
  input: GFM

title: 简悦技术Blog

members:
  cloud:   http://www.codingnow.com/
  arnan:   http://arnan.link/
  hqwrong: http://hqwrong.github.io/
  zixun:   http://www.rainbowcoder.com
  spin6lock: http://www.cnblogs.com/lifehacker
  rainfiel: http://www.rainfiel.com
  raindylong: http://thislinux.com
